package Shapes.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class Canva extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      graphics.setColor(Color.black);
      graphics.drawOval(20, 30, 400, 400);
      graphics.setColor(Color.cyan);
      graphics.drawRect(30, 20, 500, 500);
      graphics.setColor(Color.blue);
      graphics.drawRect(30, 20, 500, 500);
    }
  };

  public void initialize() {
    this.setTitle("Title");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }

  public static void main(String[] args) {
    Canva canvas = new Canva();
    canvas.initialize();
  }
}
