package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x20041ad4d4a14ef5L, 0x8cf1a8b3d7d451b0L);
    builder.put(0x568582ef7f21be98L, Canvas);
    builder.put(0x568582ef7f21be7aL, Circle);
    builder.put(0x568582ef7f22a04aL, Color);
    builder.put(0x568582ef7f248fdcL, ColorReference);
    builder.put(0x568582ef7f21be77L, Shape);
    builder.put(0x568582ef7f21be85L, Square);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
